![ 7.3_Figure-10.png](https://raw.githubusercontent.com/ksteve3/ITFDN100_MOD07/master/docs/lib/Exception%20Handling/7.3/7.3_Figure-10.png "Figure 10:  Shows new version of Try/except block after it has been manipulated using the "starter-code" used in example 7.2, Figure 7  This new Try/except block uses Python’s “Built-in” exception handlers to display multiple error message descriptions to display a variety of different errors that could occur. ")<br/><br/>Figure-10.png<br/>Source code: *[../lib/Exception Handling /7.3 /7.3_Figure-10.png   ](https://raw.githubusercontent.com/ksteve3/ITFDN100_MOD07/master/docs/lib/Exception%20Handling/7.3/7.3_Figure-10.png)     , (external link)<br/><br/>
Source code: *[../lib/Exception Handling /7.3 /7.3_Figure-10.png ](https://raw.githubusercontent.com/ksteve3/ITFDN100_MOD07/master/docs/lib/Exception%20Handling/7.3/7.3_Figure-10.png), (external link)<br/>
Source code: *[../lib/Exception Handling /7.3 /7.3_Listing-10.txt ](https://raw.githubusercontent.com/ksteve3/ITFDN100_MOD07/master/docs/lib/Exception%20Handling/7.3/7.3_Listing-10.txt), (external link)<br/>
Source code: *[../lib/Exception Handling /7.3 /7.3.py ](https://raw.githubusercontent.com/ksteve3/ITFDN100_MOD07/master/docs/lib/Exception%20Handling/7.3/7.3.py), (external link)<br/>
Source code: *[../lib/Exception Handling /7.3 /test_file.txt ](https://raw.githubusercontent.com/ksteve3/ITFDN100_MOD07/master/docs/lib/Exception%20Handling/7.3/test_file.txt), (external link)<br/>
